### ISSUE TITLE
Example 15 - Container is forced to take the size of the screen

### ISSUE THREAD

**Issue by Ruzo** [marcglasberg/flutter_layout_article#4]
In Example 15,

`OverflowBox(
   child: Container(color: red, width: 4000, height: 50));`

The red Container fills the screen instead of using its height of 50.
I'm using Flutter 2.1.0-12.2.pre.

This:
![red_container_fills_screen](https://user-images.githubusercontent.com/1992115/112632869-0d13ff00-8e0f-11eb-85ce-57255c429f0d.png)

Not this:
![red_container_wrong_example](https://user-images.githubusercontent.com/1992115/112632901-1604d080-8e0f-11eb-8864-6bc0fad9ae1c.png)

**Comment by Ruzo** [comment]
Realized that this code was fixed on the official Flutter documentation. Made a pull request to fix it here and all other small issues with code snippets.

**Comment by Ruzo** [comment]
Closed the pull request since no one is paying attention to this repo.

**Comment by marcglasberg** [comment]
@Ruzo 

Hi, you are actually right, it was unmonitored. I apologize!

For some reason the GitHub's watch feature in this repo was off, so I was not getting any warnings about issues or pull requests. I have fixed this and also checked all my repos, and found others with the same problem.

**Comment by Ruzo** [comment]
> @Ruzo
> 
> Hi, you are actually right, it was unmonitored. I apologize!
> 
> For some reason the GitHub's watch feature in this repo was off, so I was not getting any warnings about issues or pull requests. I have fixed this and also checked all my repos, and found others with the same problem.

Hi @marcglasberg, thanks a lot for letting me know. I thought it was just abandoned like others I try to help with.

By the way, if I remember correctly, I think I did see (at that time) a couple of leftover issues in the Flutter documentation but wasn't sure how to help fix it.
