### ISSUE TITLE
DartPad / Layout Article out of date

### ISSUE THREAD

**Issue by tnarik** [marcglasberg/flutter_layout_article#7]
DartPad at https://dartpad.dev/60174a95879612e500203084a0588f94? doesn't implement Null Safety, while the "same" DartPad at https://flutter.dev/docs/development/ui/layout/constraints does.

Also, for Example 16, the "BoxConstraints forces an infinite width." error is not displayed. Instead:
* The following is displayed if navigating through all examples
```
Another exception was thrown: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/foundation/stack_frame.dart:114:12
Another exception was thrown: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/box.dart:1930:12
Another exception was thrown: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdk/packages/flutter/lib/src/rendering/box.dart:1930:12
```
* A `Script Error` is displayed in the console if navigating directly to Example 16.

**Comment by marcglasberg** [comment]
Finally fixed. Thanks!
